# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 堂的博客
subtitle: 给岁月以学习,而不是给学习以岁月
description: 道不同不相为谋,懒懒的继续编程......
author: 堂
language: zh-Hans
email: LCX6916356@163.com #联系邮箱
timezone:
avatar: /uploads/avatar.jpg

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://jintang.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 2
category: 2
tag: 2

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HHbushu:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: next

# Duoshuo
duoshuo_shortname: tangqing
# Disqus
disqus_shortname: 

# Social links
social:
  GitHub: https://github.com/jintangWang
  # Weibo: http://weibo.com/iissnan
  简书: http://www.jianshu.com/users/3e9bf6c9437f
  知乎: http://www.zhihu.com/people/shu-tang-23
  豆瓣: https://www.douban.com/people/139000964/

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
    
# Creative Commons 4.0 International License.(一种许可协议)
# http://creativecommons.org/
# Available: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
creative_commons: by-nc-sa

# Google Webmaster tools verification setting(谷歌统计)
# See: https://www.google.com/webmasters/
# google_site_verification: VvyjvVXcJQa0QklHipu6pwm2PJGnnchIqX7s5JbbT_0

# Google Analytics
# Google分析ID
google_analytics: UA-78168343-1
# 百度分析ID
baidu_analytics: df56565927da6b6824f57415bffe96cf

# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

search:
  path: search.xml
  field: post

# Specify the date when the site was setup
since: 2015

# Markdown
## https://github.com/chjj/marked
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

# Stylus
stylus:
  compress: false

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:jintang/jintang.github.io.git
  branch: master